# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: context.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'context.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontext.proto\x12\x07runtime\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n\x10UserContextProto\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x39\n\x08metadata\x18\x03 \x03(\x0b\x32\'.runtime.UserContextProto.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"c\n\x0f\x43ostBudgetProto\x12\x11\n\tlimit_usd\x18\x01 \x01(\x01\x12\x11\n\tspent_usd\x18\x02 \x01(\x01\x12\x14\n\x0climit_tokens\x18\x03 \x01(\x03\x12\x14\n\x0cspent_tokens\x18\x04 \x01(\x03\"\xcd\x02\n\x0c\x43ontextProto\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\'\n\x04user\x18\x03 \x01(\x0b\x32\x19.runtime.UserContextProto\x12\x46\n\x11request_variables\x18\x04 \x03(\x0b\x32+.runtime.ContextProto.RequestVariablesEntry\x12,\n\x08\x64\x65\x61\x64line\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08priority\x18\x06 \x01(\x05\x12-\n\x0b\x63ost_budget\x18\x07 \x01(\x0b\x32\x18.runtime.CostBudgetProto\x1a\x37\n\x15RequestVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x17Z\x15\x63hukrun/proto/runtimeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'context_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025chukrun/proto/runtime'
  _globals['_USERCONTEXTPROTO_METADATAENTRY']._loaded_options = None
  _globals['_USERCONTEXTPROTO_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CONTEXTPROTO_REQUESTVARIABLESENTRY']._loaded_options = None
  _globals['_CONTEXTPROTO_REQUESTVARIABLESENTRY']._serialized_options = b'8\001'
  _globals['_USERCONTEXTPROTO']._serialized_start=60
  _globals['_USERCONTEXTPROTO']._serialized_end=218
  _globals['_USERCONTEXTPROTO_METADATAENTRY']._serialized_start=171
  _globals['_USERCONTEXTPROTO_METADATAENTRY']._serialized_end=218
  _globals['_COSTBUDGETPROTO']._serialized_start=220
  _globals['_COSTBUDGETPROTO']._serialized_end=319
  _globals['_CONTEXTPROTO']._serialized_start=322
  _globals['_CONTEXTPROTO']._serialized_end=655
  _globals['_CONTEXTPROTO_REQUESTVARIABLESENTRY']._serialized_start=600
  _globals['_CONTEXTPROTO_REQUESTVARIABLESENTRY']._serialized_end=655
# @@protoc_insertion_point(module_scope)
